DG: false
FSGD: false
PCB: false
adv: 0.0
aiter: 10
arcface: false
batchsize: 64
circle: false
color_jitter: true
contrast: false
cosface: false
cosine: false
data_dir: /home/hoang/tung/pytorch_1/pytorch/
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids:
- 0
ibn: false
ins_gamma: 32
instance: false
lifted: false
linear_num: 512
lr: 0.05
name: ft_ResNet50
nclasses: 751
sphere: false
stride: 2
total_epoch: 300
train_all: true
triplet: false
use_NAS: false
use_convnext: false
use_dense: false
use_efficient: false
use_hr: false
use_swin: false
use_swinv2: false
warm_epoch: 0
weight_decay: 0.0005
